spring:
  application:
    name: biedronka_recipes
  datasource:
    url: ${datasource.url:jdbc:postgresql://localhost:5432/PrzepisyBiedronki}
    username: ${datasource.username:postgres}
    password: ${datasource.password:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
