spring:
  application:
    name: biedronka_recipes
  datasource:
    url: ${datasource.url:jdbc:postgresql://localhost:5432/PrzepisyBiedronki}
    username: ${datasource.username:postgres}
    password: ${datasource.password:admin}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
